version: 2.1

jobs:
  build:
    machine:
      image: cimg/node:17.2.0
    steps:
      - checkout
      - run: |
          docker build . -t numamaurin14/samplejs:tagname
          docker run -p 8080:8080 -d numamaurin14/samplejs:tagname
          sleep 2
          curl -I localhost:8080 | grep "200 OK"
  publish:
    machine:
      image: cimg/node:17.2.0
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_PASSWORD -p $DOCKER_PASSWORD
          docker build . -t $DOCKER_LOGIN/samplejs:tagname
          docker image push $DOCKER_LOGIN/samplejs:tagname
workflows:
  gogo:
    jobs:
      - build
      - publish:
          requires:
            - build