version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker build . -t $DOCKER_LOGIN/samplejs
          docker run -p 8080:8080 -d $DOCKER_LOGIN/samplejs
          sleep 2
          curl -I localhost:8080 | grep "200 OK"
  publish:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker build . -t $DOCKER_LOGIN/samplejs
          docker image push $DOCKER_LOGIN/samplejs
workflows:
  dams-executor:
    jobs:
      - build
      - publish:
          requires:
            - build